logger:
  level: info
global:
  max:
    ue: 1024
smf:
  sbi:
    server:
      - address: 172.22.0.4
        port: 7777
    client:
      scp:
        - uri: http://172.22.0.11:7777
  pfcp:
    server:
      - address: 172.22.0.4
    client:
      upf:
        - address: 172.22.0.7
  gtpc:
    server:
      - address: 172.22.0.4
  gtpu:
    server:
      - address: 172.22.0.4
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
  dns:
    - 8.8.8.8
    - 1.1.1.1
  mtu: 1400
  freeDiameter: /usr/local/etc/freeDiameter/smf.conf
