logger:
  level: info
global:
  max:
    ue: 1024
upf:
  pfcp:
    server:
      - address: 172.22.0.7
  gtpu:
    server:
      - address: 172.22.0.7
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dev: ogstun
