[enb]
enb_id = 0x19B
mcc = 999
mnc = 70
mme_addr = 172.22.0.5
gtp_bind_addr = 172.22.0.40
s1c_bind_addr = 172.22.0.40
n_prb = 50

[enb_files]
sib_config = /conf/sib.conf
rr_config  = /conf/rr.conf
rb_config  = /conf/rb.conf

[rf]
device_name = zmq
device_args = fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://172.22.0.41:2100,id=enb-a,base_srate=23.04e6

[pcap]
enable = true
filename = /pcap/enb-a_mac.pcap
s1ap_enable = true
s1ap_filename = /pcap/enb-a_s1ap.pcap

[log]
all_level = info
filename = stdout

[expert]
