[rf]
device_name = zmq
device_args = tx_port=tcp://*:2001,rx_port=tcp://172.22.0.41:2111,id=ue1,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 3350
nof_carriers = 1

[usim]
mode = soft
algo = milenage
opc  = E8ED289DEBA952E4283B54E88E6183CA
k    = 465B5CE8B199B49FAA5F0A2EE238A6BC
imsi = 999700000000001
imei = 353490069873319

[nas]
apn = internet

[gw]
netns =

[pcap]
enable = mac,nas
mac_filename = /pcap/ue1_mac.pcap
nas_filename = /pcap/ue1_nas.pcap

[log]
all_level = info
filename = stdout
