[rf]
device_name = zmq
device_args = tx_port=tcp://*:2001,rx_port=tcp://172.22.0.41:2112,id=ue2,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 3350
nof_carriers = 1

[usim]
mode = soft
algo = milenage
opc  = 000102030405060708090A0B0C0D0E0F
k    = 00112233445566778899AABBCCDDEEFF
imsi = 999700000000002
imei = 353490069873319

[nas]
apn = internet

[gw]
netns =

[pcap]
enable = mac,nas
mac_filename = /pcap/ue2_mac.pcap
nas_filename = /pcap/ue2_nas.pcap

[log]
all_level = info
filename = stdout
