[rf]
device_name = zmq
device_args = tx_port=tcp://*:2001,rx_port=tcp://172.22.0.51:2111,id=ue3,base_srate=23.04e6

[rat.eutra]
dl_earfcn = 3350
nof_carriers = 1

[usim]
mode = soft
algo = milenage
opc  = 0F0E0D0C0B0A09080706050403020100
k    = 8899AABBCCDDEEFF0011223344556677
imsi = 999700000000003
imei = 353490069873319

[nas]
apn = internet

[gw]
netns =

[pcap]
enable = mac,nas
mac_filename = /pcap/ue3_mac.pcap
nas_filename = /pcap/ue3_nas.pcap

[log]
all_level = info
filename = stdout
